### ISSUE TITLE
Unable to configure

### ISSUE THREAD

**Issue by gustavstrandberg** [CJNE/thermiagenesis#1]
Trying to connect to my Thermia Atlas 12 via Modbus TCP.
Modbus TCP is enabled in my heatpump.

When I try to configure the integration I get the error message "User input malformed".

![image](https://user-images.githubusercontent.com/38432101/144998648-433eeb2b-40e7-47ac-8b9f-32e4445832df.png)

I do not know if it should be possible to connect to an Atlas 12 but it is running Genesis just like the inverter and mega heatpumps. I need help to point me in the right direction...

thanks,
Gustav

**Comment by CJNE** [comment]
Hi!
I haven't touched this integration in quite some time, this was probably caused by some change in home assistant.
I have published a new version, 0.0.7, that should fix this!

**Comment by gustavstrandberg** [comment]
Tackar för hjälpen.
Jag testar på nytt.

Mvh
Gustav

**Comment by gustavstrandberg** [comment]
Still unable to configure. I updated to version 0.0.7 (via HACS) and the files are installed in the wrong directory.
To get the integration as an option I had to rename the directory under custom_components and make a symbolic link to  the .py-files. 
/config/custom_components/thermiagenesis -> /config/custom_components/thermiagenesis_github/custom_components/thermiagenesis

The plugin is now shown in the integration but when I try to run it it just freezes. I cannot find any error messages in the home assistant logfiles.

![image](https://user-images.githubusercontent.com/38432101/145418419-b1b06f28-e6d5-4cc8-95b7-3692d4f1ea11.png)

I am running Home Assistant 2021.11.5 aarch64 on a Raspberrypi 4.

Please advice.
Thanks,
Gustav

**Comment by matake31** [comment]
It worked like a charm for me until the 0.0.7 update that stopped everthing. Backed down to 0.0.6 and it's back to working again.
It looks like 0.0.7 is moving the files to a catlog under the right one.

**Comment by gustavstrandberg** [comment]
As a desperate move I rebooted the Pi and now everything started working.
I guess moving the files to the correct path and a reboot did the trick :-).

**Comment by gustavstrandberg** [comment]
So to summarize. The problem is that the files are placed in the wrong path "/config/custom_components/thermiagenesis/custom_components/thermiagenesis"

**Comment by CJNE** [comment]
My bad, i reorganized the directory structure, previously everything was located in the root directory of this repo and now it's in custom_components/thermiagenesis.
For new installations it works without any issues but when you update an existing install it seems to break. 
So to get around this you can do this:
- Remove the integration form home assistant integrations page 
- Uninstall the integration in HACS
- Restart (don't skip this step otherwise it will install in the wrong dir)
- Install the integratoin in HACS
- Restart
- Reload the browser window (might not be needed for you but i had to).
- Add the integration on the integrations page.

Your entities should have the same id's so your history is preserved.

Nice to see that someone is using this, i'm going to add some features to it in the near future, like being able to write all values that are settable.

**Comment by matake31** [comment]
Jag har tom frågat tekniker på Thermia om de inte skulle släppa ett API (var tydligen inte aktuellt just nu) i vilket fall har jag en atlas 18 som fungerar fin fint. Å din plugin hjälper till att hålla lite koll och rita kurvor :-D

**Comment by senilio** [comment]
I will use it as well, if I can just figure out how to enable Modbus TCP on the Atlas 18 😅

**Comment by gustavstrandberg** [comment]
> I will use it as well, if I can just figure out how to enable Modbus TCP on the Atlas 18 😅

You can use the service code 607080 activate BMS in the display settings. There you can choose Modbus TCP or RTU.
