### ISSUE TITLE
Failed to format translation for key 'component.thermiagenesis.title' in language 'en'. Error: The intl string context variable "model" was not provided to the string "Thermia Heatpump: {model}"

### ISSUE THREAD

**Issue by KristianOellegaard** [CJNE/thermiagenesis#293]
## Version of the custom_component

0.0.11

## Describe the bug

The integrations title has a variable in it that is not provided causing it to make a lot of errors and show up wrong in HA:

<img width="365" alt="Image" src="https://github.com/user-attachments/assets/d6fba97f-7572-44dc-89c2-7af45b146e77" />

## Debug log

```text

Logger: frontend.js.modern.202504110
Source: components/system_log/__init__.py:331
First occurred: 9:14:14 PM (854 occurrences)
Last logged: 10:08:55 PM

Failed to format translation for key 'component.thermiagenesis.title' in language 'en'. Error: The intl string context variable "model" was not provided to the string "Thermia Heatpump: {model}"
```

**Comment by KristianOellegaard** [comment]
Looks like it was solved on a fork here: https://github.com/4tbs/thermiagenesis/commit/cfcd49b395bf043ecd5e5fea1e150515ce143b81 by @4tbs would be great if this could be merged in

**Comment by jarru66** [comment]
This same error faced now, when upgrading Core from 2025.5.3 to 2025.6.3.
I uploaded those 8 fixed files manually to my HA, rebooted the whole system, but still getting the same error msg:
Translation Error: The intl string context variable "model" was not provided to the string "Thermia Heatpump: {model}"
